"""Native macOS integration tools package."""

from core.tools.native_macos.calendar import (
    CreateEventInput,
    CreateEventTool,
    DeleteEventInput,
    DeleteEventTool,
    GetEventInput,
    GetEventTool,
    ListCalendarsInput,
    ListCalendarsTool,
    ListEventsInput,
    ListEventsTool,
    UpdateEventInput,
    UpdateEventTool,
)
from core.tools.native_macos.notifications import (
    CancelNotificationInput,
    CancelNotificationTool,
    NotificationStatusInput,
    NotificationStatusTool,
    ScheduleNotificationInput,
    ScheduleNotificationTool,
    ShowNotificationInput,
    ShowNotificationTool,
)
from core.tools.native_macos.provider import register_apple_tools
from core.tools.native_macos.reminders import (
    CompleteReminderInput,
    CompleteReminderTool,
    CreateReminderInput,
    CreateReminderTool,
    DeleteReminderInput,
    DeleteReminderTool,
    ListReminderListsInput,
    ListReminderListsTool,
    ListRemindersInput,
    ListRemindersTool,
    UpdateReminderInput,
    UpdateReminderTool,
)

__all__ = [
    "CancelNotificationInput",
    "CancelNotificationTool",
    "CompleteReminderInput",
    "CompleteReminderTool",
    "CreateEventInput",
    "CreateEventTool",
    "CreateReminderInput",
    "CreateReminderTool",
    "DeleteEventInput",
    "DeleteEventTool",
    "DeleteReminderInput",
    "DeleteReminderTool",
    "GetEventInput",
    "GetEventTool",
    "ListCalendarsInput",
    "ListCalendarsTool",
    "ListEventsInput",
    "ListEventsTool",
    "ListReminderListsInput",
    "ListReminderListsTool",
    "ListRemindersInput",
    "ListRemindersTool",
    "NotificationStatusInput",
    "NotificationStatusTool",
    "ScheduleNotificationInput",
    "ScheduleNotificationTool",
    "ShowNotificationInput",
    "ShowNotificationTool",
    "UpdateEventInput",
    "UpdateEventTool",
    "UpdateReminderInput",
    "UpdateReminderTool",
    "register_apple_tools",
]
